# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_label_source_unreliablesource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Default description'),
        ),
        migrations.AlterField(
            model_name='label',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Default label'),
        ),
    ]
