# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171122_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='description',
            field=models.TextField(),
        ),
    ]
