# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 21:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171111_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='result',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=300), default=[], size=None),
        ),
        migrations.AddField(
            model_name='result',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=300), default=[], size=None),
        ),
        migrations.AddField(
            model_name='result',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='result',
            name='videos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=300), default=[], size=None),
        ),
    ]
