# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 21:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171112_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='result',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='result',
            name='videos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), default=[], size=None),
        ),
    ]
