# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171112_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='description',
            field=models.CharField(default='description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='result',
            name='title',
            field=models.CharField(default='title', max_length=500),
        ),
    ]
