# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20171112_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
