# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20171112_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='description',
        ),
        migrations.RemoveField(
            model_name='result',
            name='title',
        ),
    ]
