# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20171112_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='author',
            field=models.CharField(default='author', max_length=200),
        ),
    ]
