# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20171112_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='UntrustedSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.CharField(max_length=300)),
            ],
        ),
    ]
